### ISSUE TITLE
[Pedometer] Pedometer starts accessing device sensor list on app launch #3

### ISSUE THREAD

**Issue by knight0zh** [cph-cachet/flutter-plugins#1004]
This behavior is causing the app to fail privacy compliance reviews on certain platforms.

Can anyone help me understand why this is happening and how to prevent the plugin from accessing the device's sensor list on app launch?

Stack info:
at android.hardware.SensorManager.getSensorList()
at android.hardware.SensorManager.getDefaultSensor(SensorManager.java:488)
at n1.c.(Unknown Source:56)
at n1.a.onAttachedToEngine(Unknown Source:35)
at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(Unknown Source:110)
at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:296)
at java.lang.reflect.Method.invoke(Native Method)
at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(Unknown Source:21)
at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(Unknown Source:9)
at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(Unknown Source:58)
at io.flutter.embedding.android.FlutterActivity.onCreate(Unknown Source:13)
at android.app.Activity.performCreate(Activity.java:7009)
at android.app.Activity.performCreate(Activity.java:7000)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2784)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2909)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6554)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:558)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

**Comment by Jazzzy126** [comment]
I also encountered this issue on my end, which caused me to request the sensor before agreeing to the privacy agreement and unable to upload the app. Have you fixed it
