### ISSUE TITLE
Exception in currentWeather() call

### ISSUE THREAD

**Issue by bardram** [cph-cachet/flutter-plugins#16]
When calling `currentWeather()` it thrown an exception:

````
E/flutter ( 2551): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter ( 2551): Receiver: null
E/flutter ( 2551): Tried calling: [](0)
E/flutter ( 2551): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
E/flutter ( 2551): #1      new Weather (package:weather/weather.dart:108:58)
E/flutter ( 2551): #2      WeatherStation.currentWeather (package:weather/weather.dart:235:16)
E/flutter ( 2551): <asynchronous suspension>
E/flutter ( 2551): #3      WeatherProbe.getDatum (package:carp_context_package/weather_probe.dart:15:32)
````

which points to the last line in this part of the weather plugin:

````
/// A class for storing a weather-query response from OpenWeatherMap.
/// This includes various measures such as location,
/// temperature, wind, snow, rain and humidity.
class Weather {
  String _country, _areaName, _weatherMain, _weatherDescription, _weatherIcon;
  Temperature _temperature, _tempMin, _tempMax;
  DateTime _date, _sunrise, _sunset;
  double _latitude,
      _longitude,
      _pressure,
      _windSpeed,
      _windDegree,
      _humidity,
      _cloudiness,
      _rainLastHour,
      _rainLast3Hours,
      _snowLastHour,
      _snowLast3Hours;

  Weather(Map<String, dynamic> weatherData) {
    Map<String, dynamic> main = weatherData['main'];
    Map<String, dynamic> coord = weatherData['coord'];
    Map<String, dynamic> sys = weatherData['sys'];
    Map<String, dynamic> wind = weatherData['wind'];
    Map<String, dynamic> clouds = weatherData['clouds'];
    Map<String, dynamic> rain = weatherData['rain'];
    Map<String, dynamic> snow = weatherData['snow'];
    Map<String, dynamic> weather = weatherData['weather'][0];
````

**Comment by thomasnilsson** [comment]
Will have a look this weekend

**Comment by thomasnilsson** [comment]
New exceptions have been added, and meaningful exceptions with a corresponding message should be thrown now. It is likely a bad API key was used, or location permissions were not given.
In addition to this, the instructions in the README slightly, to make sure the instructions are clear.

Report back if the problem persists!

**Comment by bardram** [comment]
I get a 

````
SocketException: Failed host lookup: 'api.openweathermap.org' (OS Error: No address associated with hostname, errno = 7)
````

error. Can this be an expired API key?

**Comment by bardram** [comment]
Seems to work now.
