### ISSUE TITLE
[Health 3.1.1+1] Fatal Error on getData

### ISSUE THREAD

**Issue by rsbthebest** [cph-cachet/flutter-plugins#415]
Happening on real devices.

Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: Galaxy s10 5G
 - OS: Android 11

We are noticing crashes on Android and IOS from the health plugin. This is what we have on crashlytics:

Fatal Exception: i.b
       at cachet.plugins.health.HealthPlugin$getData$1.a(HealthPlugin.java:438)
       at cachet.plugins.health.HealthPlugin$getData$1.invoke(HealthPlugin.java)
       at kotlin.concurrent.ThreadsKt$thread$thread$1.run(ThreadsKt.java:2)
ReferenceQueueDaemon
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:217)
       at java.lang.Daemons$Daemon.run(Daemons.java:139)
       at java.lang.Thread.run(Thread.java:923)

Please have a look and help us out!

**Comment by rsbthebest** [comment]
Hey Team, any one looking into this?

**Comment by bardram** [comment]
Fixed (addressed) as part of PR #483 and released as version 3.4.1. 

Thanks to @matsunanaro for the PR.
