### ISSUE TITLE
[3.2.1] Android crash HealthPlugin.java line 434

### ISSUE THREAD

**Issue by hukusuke1007** [cph-cachet/flutter-plugins#470]
### Device / Emulator and OS

 - Device: AQUOS sense3 basic, Galaxy S10, AQUOS sense3 plus (901SH), Mi 10 Lite 5G
 - OS: Android10, 11

### Describe the bug
This is logs in Crashlytics dashboard.

```
Fatal Exception: j.d
       at cachet.plugins.health.HealthPlugin$getData$1.invoke(HealthPlugin.java:434)
       at cachet.plugins.health.HealthPlugin$getData$1.invoke(HealthPlugin.java)
       at kotlin.concurrent.ThreadsKt$thread$thread$1.run(ThreadsKt.java:2)
```

### To Reproduce
Run application.

### Expected behavior
No crash.

### Actual behavior
Crash.

### Screenshots
None

### Flutter doctor 

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale ja-JP)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2018.3.3)
[✓] VS Code (version 1.62.3)
[✓] Connected device (1 available)
```

### Additional information
This is release mode.

**Comment by bardram** [comment]
Fixed (addressed) as part of PR #483 and released as version 3.4.1. 

Thanks to @matsunanaro for the PR.
