### ISSUE TITLE
Crash in Android -  java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by ss-strive** [cph-cachet/flutter-plugins#478]
### Flutter Plugin 
health: ^3.3.1

### Device and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: POCO F1, Samsung M11 
 - OS: Android 11.0

### Issue:
I have an app that tracks users' activity via Goggle FIT. I have correctly set up all the OAuth and the app works fine and I am able to see the Google mail selector pop-ups and seamlessly connect to FIT.

However, on the first attempt of OAuth connection if users cancel the Google dialog by tapping outside the pop-up then re-launch the OAuth and cancel it again. The app crashes with the following error - `Caused by: java.lang.IllegalStateException: Reply already submitted`

Here are the video and logs for your reference.

Video leading to the crash - [Crash Video](https://drive.google.com/file/d/1tmDRmp_ZfD492Rm3sKuB7w05M06YMBRu/view?usp=sharing)

Logs:
D/FLUTTER_HEALTH(30352): Access Denied!
D/AndroidRuntime(30352): Shutting down VM
E/AndroidRuntime(30352): FATAL EXCEPTION: main
E/AndroidRuntime(30352): Process: com.recode.woodruff, PID: 30352
E/AndroidRuntime(30352): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1111, result=0, data=Intent { (has extras) }} to activity {com.recode.woodruff/com.strivebenefits.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(30352): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4938)
E/AndroidRuntime(30352): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4979)
E/AndroidRuntime(30352): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(30352): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(30352): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(30352): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
E/AndroidRuntime(30352): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(30352): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(30352): 	at android.app.ActivityThread.main(ActivityThread.java:7562)
E/AndroidRuntime(30352): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30352): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(30352): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(30352): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(30352): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:164)
E/AndroidRuntime(30352): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime(30352): 	at cachet.plugins.health.HealthPlugin.onActivityResult(HealthPlugin.kt:130)
E/AndroidRuntime(30352): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:741)
E/AndroidRuntime(30352): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:426)
E/AndroidRuntime(30352): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:749)
E/AndroidRuntime(30352): 	at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:916)
E/AndroidRuntime(30352): 	at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:534)
E/AndroidRuntime(30352): 	at android.app.Activity.dispatchActivityResult(Activity.java:8249)
E/AndroidRuntime(30352): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4931)
E/AndroidRuntime(30352): 	... 11 more
I/Process (30352): Sending signal. PID: 30352 SIG: 9

Also Attaching `flutter doctor -v` info:
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.1 21C52 darwin-x64, locale en-IN)
    • Flutter version 2.5.3 at /Users/shekharsuman/FlutterSDK/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (9 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/shekharsuman/Library/Android/sdk
    • Platform android-Sv2, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.
[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      :hammer: https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      :hammer: https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
[✓] VS Code (version 1.63.1)
    • VS Code at /Users/shekharsuman/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0
[✓] Connected device (2 available)
    • POCO F1 (mobile) • 3206e803 • android-arm64  • Android 10 (API 29)
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 96.0.4664.110
! Doctor found issues in 1 category.

**Comment by MlecznyU** [comment]
I have a similar problem 

D/FLUTTER_HEALTH(30353): Access Denied!
D/FLUTTER_HEALTH(30353): Access Granted!
E/AndroidRuntime(30353): FATAL EXCEPTION: main
E/AndroidRuntime(30353): Process: ai.mxlabs.heartmonitor, PID: 30353
E/AndroidRuntime(30353): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1111, result=-1, data=Intent { (has extras) }} to activity {ai.mxlabs.heartmonitor/ai.mxlabs.heartmonitor.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(30353): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5195)
E/AndroidRuntime(30353): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5236)
E/AndroidRuntime(30353): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(30353): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(30353): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(30353): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2187)
E/AndroidRuntime(30353): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(30353): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime(30353): 	at android.app.ActivityThread.main(ActivityThread.java:8057)
E/AndroidRuntime(30353): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30353): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
E/AndroidRuntime(30353): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
E/AndroidRuntime(30353): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(30353): 	at nb.c$e.a(DartMessenger.java:4)
E/AndroidRuntime(30353): 	at ac.j$a$a.a(MethodChannel.java:1)
E/AndroidRuntime(30353): 	at k1.n.b(HealthPlugin.kt:4)
E/AndroidRuntime(30353): 	at io.flutter.embedding.engine.c$c.f(FlutterEngineConnectionRegistry.java:2)
E/AndroidRuntime(30353): 	at io.flutter.embedding.engine.c.b(FlutterEngineConnectionRegistry.java:4)
E/AndroidRuntime(30353): 	at io.flutter.embedding.android.d.n(FlutterActivityAndFragmentDelegate.java:4)
E/AndroidRuntime(30353): 	at io.flutter.embedding.android.h.t0(FlutterFragment.java:2)
E/AndroidRuntime(30353): 	at io.flutter.embedding.android.i.onActivityResult(FlutterFragmentActivity.java:2)
E/AndroidRuntime(30353): 	at android.app.Activity.dispatchActivityResult(Activity.java:8516)
E/AndroidRuntime(30353): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5188)
E/AndroidRuntime(30353): 	... 11 more

**Comment by mundramanish** [comment]
Health package working in iOS, but getting crash in Android on tap on choose Email 3.4.3 version
Please help to solve this issue 

D/FLUTTER_HEALTH( 7998): Access Denied!
D/AndroidRuntime( 7998): Shutting down VM
E/AndroidRuntime( 7998): FATAL EXCEPTION: main
E/AndroidRuntime( 7998): Process: com.energym, PID: 7998
E/AndroidRuntime( 7998): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1111, result=0, data=Intent { (has extras) }} to activity {com.energym/com.energym.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 7998): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5108)
E/AndroidRuntime( 7998): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5149)
E/AndroidRuntime( 7998): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime( 7998): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime( 7998): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime( 7998): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
E/AndroidRuntime( 7998): 	at android.os.Handler.dispatchMessage(Handler.java:106)

**Comment by bardram** [comment]
> Any new info?

We're looking into it now.

**Comment by MadsVSChristensen** [comment]
I've published 4.6.0 which should fix it. I've tested it extensively, but let me know if this is still an issue.

**Comment by MaddinMade** [comment]
This currently happens to me with every requestAuthorization call in version 5.0.0:
```
java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime( 8060): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/AndroidRuntime( 8060): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:263)
E/AndroidRuntime( 8060): 	at cachet.plugins.health.HealthPlugin.onActivityResult(HealthPlugin.kt:247)
E/AndroidRuntime( 8060): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:807)
E/AndroidRuntime( 8060): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:430)
E/AndroidRuntime( 8060): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:811)
E/AndroidRuntime( 8060): 	at io.flutter.embedding.android.FlutterFragment.onActivityResult(FlutterFragment.java:964)
E/AndroidRuntime( 8060): 	at io.flutter.embedding.android.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:566)
E/AndroidRuntime( 8060): 	at android.app.Activity.dispatchActivityResult(Activity.java:8316)
E/AndroidRuntime( 8060): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5237)
```
