### ISSUE TITLE
when i use the demo 

### ISSUE THREAD

**Issue by faizahmaddae** [cph-cachet/flutter-plugins#489]
D/InputTransport( 3435): Input channel destroyed: 'ClientS', fd=97
I/ViewRootImpl@4a7cff3[MainActivity]( 3435): stopped(true) old=false
D/AndroidRuntime( 3435): Shutting down VM
E/AndroidRuntime( 3435): FATAL EXCEPTION: main
E/AndroidRuntime( 3435): Process: org.notifications.reader, PID: 3435
E/AndroidRuntime( 3435): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
E/AndroidRuntime( 3435): 	at dk.cachet.notifications.NotificationListener.onNotificationPosted(NotificationListener.java:40)
E/AndroidRuntime( 3435): 	at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:375)
E/AndroidRuntime( 3435): 	at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2166)
E/AndroidRuntime( 3435): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 3435): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime( 3435): 	at android.app.ActivityThread.main(ActivityThread.java:8577)
E/AndroidRuntime( 3435): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3435): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime( 3435): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
I/Process ( 3435): Sending signal. PID: 3435 SIG: 9

**Comment by shinewanna** [comment]
Facing same issue, any fix??
