### ISSUE TITLE
SWIFT_VERSION attribute is missing

### ISSUE THREAD

**Issue by bardram** [cph-cachet/flutter-plugins#50]
**Plugin name & version**

- `app_usage`
- `light`
- `pedometer`
- `screen_state`

and maybe others?

**Describe the bug**

When running `pod install` for iOS deployment, it says that `SWIFT_VERSION` attribute is not set. This is the output.

```
      - Running pre install hooks
    [!] Unable to determine Swift version for the following pods:

    - `app_usage` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
    - `light` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
    - `pedometer` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
    - `screen_state` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/target_validator.rb:122:in `verify_swift_pods_swift_version'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:578:in `validate_targets'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:158:in `install!'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/command/install.rb:51:in `run'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.7.5/libexec/bin/pod:22:in `<main>'
```

**To Reproduce**

Try to build the example (`main.dart`) in the carp_mobile_sensing package.

**Expected behavior**

Other plugins which is loaded does not have these problems.

**Flutter doctor**
Please run `flutter doctor` and add the output here.

**Smartphone(s) / Emulator**

iPhone XP - iOS 13.3

**Additional context**

**Comment by bardram** [comment]
See https://github.com/ko2ic/image_downloader/issues/9#issuecomment-471186536 for a similar problem / solution.

**Comment by thomasnilsson** [comment]
The mentioned plugins will get an overhaul in terms of their Flutter API code.
