### ISSUE TITLE
notifications: ^2.0.1     -----   After accessing null object, App gets force closed

### ISSUE THREAD

**Issue by KoolAbhi03** [cph-cachet/flutter-plugins#583]
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
E/AndroidRuntime( 5827):        at dk.cachet.notifications.NotificationListener.onNotificationPosted(NotificationListener.java:40)
E/AndroidRuntime( 5827):        at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:374)  
E/AndroidRuntime( 5827):        at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2131)
E/AndroidRuntime( 5827):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 5827):        at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime( 5827):        at android.app.ActivityThread.main(ActivityThread.java:7861)
E/AndroidRuntime( 5827):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5827):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
E/AndroidRuntime( 5827):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

After accessing null object, App gets force closed

**Comment by mitryp** [comment]
Hi! 
I've got the same NullPointer too. My issue was [in April](https://github.com/cph-cachet/flutter-plugins/issues/541), and there is still no reaction, so I think this package is abandoned. In my issue discussion, there was a link to another package with better functionality.
Hope this will help
