### ISSUE TITLE
noise_meter (audio_streamer) error: android.media.AudioRecord.native_read_in_short_array(AudioRecord.java)

### ISSUE THREAD

**Issue by maliaydemir** [cph-cachet/flutter-plugins#594]
App gets crash on this error: 
`Thread-10
       at android.media.AudioRecord.native_read_in_short_array(AudioRecord.java)
       at android.media.AudioRecord.read(AudioRecord.java:1262)
       at android.media.AudioRecord.read(AudioRecord.java:1216)
       at plugins.cachet.audio_streamer.AudioStreamerPlugin.streamMicData$lambda-1(AudioStreamerPlugin.java:53)
       at plugins.cachet.audio_streamer.AudioStreamerPlugin.lambda$InWbN0dYFprPX2LbqCuF81gN6Dw(AudioStreamerPlugin.java)
       at plugins.cachet.audio_streamer.-$$Lambda$AudioStreamerPlugin$InWbN0dYFprPX2LbqCuF81gN6Dw.run(-.java:2)
       at java.lang.Thread.run(Thread.java:764)`

I am getting error log from FirebaseCrashlytics. Does any one can help for solution?
Device
Brand:OPPO
Model:CPH2015
Orientation: Portrait
RAM free: 1.78 GB
Disk free: 18.42 GB

Operating System
Version:Android 9
Orientation: Portrait
Rooted:No

**Comment by bardram** [comment]
Fixed with noise_meter version 4.0.1
