### ISSUE TITLE
notifications: ^2.0.1 - Android APP Keep Stopping in Samsung Device

### ISSUE THREAD

**Issue by mahesh-gubbi** [cph-cachet/flutter-plugins#614]
### Device / Emulator and OS
 - Device: [e.g. Samsung ]
 - OS: [e.g. Android 12]

### Describe the bug
notifications: ^2.0.1 used to fetch Notifications but when app app background sometimes app keep stopping particularly in dial pad   app is crashed.

```
Shutting down VM
E/AndroidRuntime( 9928): FATAL EXCEPTION: main
E/AndroidRuntime( 9928): Process: com.example.testapp, PID: 9928
E/AndroidRuntime( 9928): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
E/AndroidRuntime( 9928): 	at dk.cachet.notifications.NotificationListener.onNotificationPosted(NotificationListener.java:41)
E/AndroidRuntime( 9928): 	at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:444)
E/AndroidRuntime( 9928): 	at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2337)
E/AndroidRuntime( 9928): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 9928): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime( 9928): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime( 9928): 	at android.app.ActivityThread.main(ActivityThread.java:8751)
E/AndroidRuntime( 9928): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9928): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime( 9928): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
I/Process ( 9928): Sending signal. PID: 9928 SIG: 9
```

### Screenshot
![Screenshot_20221028-103904_Phone](https://user-images.githubusercontent.com/115148874/198508927-de06b442-c253-40d8-bd2f-62cf8798bfa8.jpg)
ts

**Comment by mahesh-gubbi** [comment]
hi team, can i get some details about this, what's the changes my side code.

**Comment by mahesh-gubbi** [comment]
hi team, can i get some details about this, what's the changes my side code.
