### ISSUE TITLE
Notification plugin causing app crash when receiving new notification

### ISSUE THREAD

**Issue by imchivaa** [cph-cachet/flutter-plugins#64]
**Plugin name & version**
Plugin Name: Notifications
Plugin Version: 0.0.3

**Describe the bug**
Exception on OnReceive method causing app to crash.

**To Reproduce**
Followed sample guide in readme and from the example project.

**Expected behavior**
N/A

**Actual behavior**
N/A

**Screenshots**
N/A

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.720], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] Connected device (1 available)

• No issues found!
```

**Smartphone(s) / Emulator**
Please complete the following information for each phone and/or emulator you're experiencing this bug on:

 - Device: Xiaomi Mi A2
 - OS: Android 10

**Additional context**
Stacktrace
```
E/AndroidRuntime(19158): java.lang.RuntimeException: Error receiving broadcast Intent { act=notification_event flg=0x10 (has extras) } in cachet.plugins.notifications.NotificationsPlugin$NotificationReceiver@f6cccc4
E/AndroidRuntime(19158): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1560)
E/AndroidRuntime(19158): 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
E/AndroidRuntime(19158): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(19158): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(19158): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(19158): 	at android.app.ActivityThread.main(ActivityThread.java:7397)
E/AndroidRuntime(19158): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19158): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(19158): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:920)
E/AndroidRuntime(19158): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.EventChannel$EventSink.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(19158): 	at cachet.plugins.notifications.NotificationsPlugin$NotificationReceiver.onReceive(NotificationsPlugin.java:107)
E/AndroidRuntime(19158): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1550)
E/AndroidRuntime(19158): 	... 8 more
```

**Comment by KingDarBoja** [comment]
This is weird as the package does work in my [custom project](https://github.com/KingDarBoja/Notification-Listener). Can you share your `pubspec.yml` file?

**Comment by imchivaa** [comment]
Sorry, couldn't provide the pubspec.yml since i moved to native for notification listener service. Issue can be closed.

**Comment by mohit67890** [comment]
Hi, I'm facing the same issue. Please help
