### ISSUE TITLE
[Health 6.0.0] multiple CRASHES on Android 12, 13 with RuntimeException

### ISSUE THREAD

**Issue by rafaellop** [cph-cachet/flutter-plugins#708]
### Device / Emulator and OS
Please complete the following information for each phone and/or emulator you're experiencing this bug on:
 - Device: production version, different devices like S22 Ultra, Redmi 11 Pro+
 - OS: Android 12, Android 13

### Describe the bug

The Google Play "Crashes and ANR" section reports crashes on users devices in production version which uses the newest plugin version 6.0.0.

### To Reproduce

Can't tell exactly. It happens on users devices when accessing Google Fit data.

### Expected behavior

Not crashing

### Actual behavior

```
Exception java.lang.RuntimeException:
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5994)
  at android.app.ActivityThread.handleSendResult (ActivityThread.java:6033)
  at android.app.servertransaction.ActivityResultItem.execute (ActivityResultItem.java:67)
  at android.app.servertransaction.ActivityTransactionItem.execute (ActivityTransactionItem.java:45)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2574)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8757)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)
Caused by java.lang.IllegalStateException: Reply already submitted
  at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply (DartMessenger.java)
  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success (MethodChannel.java)
  at cachet.plugins.health.HealthPlugin.onActivityResult (HealthPlugin.java)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult (FlutterEngineConnectionRegistry.java)
  at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult (FlutterEngineConnectionRegistry.java)
  at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult (FlutterActivityAndFragmentDelegate.java)
  at io.flutter.embedding.android.FlutterActivity.onActivityResult (FlutterActivity.java)
  at android.app.Activity.dispatchActivityResult (Activity.java:8951)
  at android.app.ActivityThread.deliverResults (ActivityThread.java:5987)
```

### Flutter doctor 

```
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.22000.1696])
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.77.3)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

**Comment by hoffmatteo** [comment]
Are you using the example app and which function causes the application to crash?

**Comment by rafaellop** [comment]
As I wrote the crash happens in production and it happens to users not me. In fact I'm unable to reproduce this but my Google Play started to be flooded by crash reports like the abovementioned so I had to withdraw the version and replace it with a last stable.

**Comment by rikaweb** [comment]
after upgrading to version 6.0.0
I got this error on Andriod:


E/AndroidRuntime(28117): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:807)
E/AndroidRuntime(28117): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:430)
E/AndroidRuntime(28117): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:811)
E/AndroidRuntime(28117): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:771)
E/AndroidRuntime(28117): 	at android.app.Activity.dispatchActivityResult(Activity.java:8608)
E/AndroidRuntime(28117): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5337)
E/AndroidRuntime(28117): 	... 13 more
D/EGL_emulation(28117): app_time_stats: avg=37.29ms min=3.43ms max=428.35ms count=26
D/EGL_emulation(28117): app_time_stats: avg=18.62ms min=13.53ms max=126.58ms count=54
W/.portionsmaster(28117): Cleared Reference was only reachable from finalizer (only reported once)
W/JavaBinder(28117): BinderProxy is being destroyed but the application did not call unlinkToDeath to unlink all of its death recipients beforehand.  Releasing leaked death recipient: com.google.android.play.core.review.internal.zzl
I/BpBinder(28117): onLastStrongRef automatically unlinking death recipients: <uncached descriptor>
W/System  (28117): A resource failed to call end.

**Comment by rafaellop** [comment]
For what I suspect the problem occurs when there are several or even just two subsequent or almost parallel calls to the authorization API.

**Comment by sumeetInpaqt** [comment]
I Fixed a problem by setting "useHealthConnectIfAvailable: false". I had set this parameter to "true" and I don't think the plugin has fully implemented Healthconnect or there just isn't enough documentation on how to get it working. 

I also think that the Scopes that the health plugin uses are restricted on Android 12, and 13, and even after putting the required permission in Manifest you need to ask specific permissions to the user at run time. For example, if you have put "android.permission.health.READ_STEPS" you need to ask permissions for this scope which permission_handler is not equipped to handle. 

I am saying this because I would get "java.lang.SecurityException: [android.permission.health.READ_STEPS] is not declared!" error and the app would crash even though I had requested permission in the manifest. It's just a theory at this point.
