### ISSUE TITLE
[Health 6.0.0] Unable to get permissions in Android Health Connect

### ISSUE THREAD

**Issue by mototakatsu** [cph-cachet/flutter-plugins#732]
**Remember to specify the plugin name in the title!**

### Device / Emulator and OS
 - Device: Pixel 7
 - OS: Android 13

### Describe the bug
When HealthConnect is targeted, the authority cannot be obtained and the data cannot be obtained.

### To Reproduce
```
  Future<void> _syncHealth() async {
    await Permission.activityRecognition.request();
    HealthFactory health = HealthFactory(useHealthConnectIfAvailable: true);
    const types = [
      HealthDataType.STEPS,
    ];
    const permissions = [
      HealthDataAccess.READ,
    ];
    bool requested =
        await health.requestAuthorization(types, permissions: permissions);
    debugPrint("requestAuthorization requested: $requested");
    if (!requested) {
      setState(() {
        _message = "Authorization failed";
      });
      return;
    }
    bool? hasPermissions =
        await health.hasPermissions(types, permissions: permissions);
    debugPrint("hasPermissions: $hasPermissions");

    var now = DateTime.now();
    var midnight = DateTime(now.year, now.month, now.day);
    List<HealthDataPoint> healthData =
        await health.getHealthDataFromTypes(midnight, now, types);
    ...
}
```

### Expected behavior
Permissions can be obtained and data can be obtained.

### Actual behavior
```
I/.flutter_health( 5621): Compiler allocated 4413KB to compile void android.view.ViewRootImpl.performTraversals()
D/CompatibilityChangeReporter( 5621): Compat change id reported: 78294732; UID 10405; state: ENABLED
I/FLUTTER_HEALTH( 5621): Access Granted (to Health Connect)!
I/flutter ( 5621): requestAuthorization requested: true
I/flutter ( 5621): hasPermissions: false
E/AndroidRuntime( 5621): FATAL EXCEPTION: main
E/AndroidRuntime( 5621): Process: com.asken.flutter_health, PID: 5621
E/AndroidRuntime( 5621): java.lang.SecurityException: [android.permission.health.READ_STEPS] is not declared!
E/AndroidRuntime( 5621): 	at androidx.health.platform.client.impl.error.ErrorStatusConverterKt.toException(ErrorStatusConverter.kt:47)
E/AndroidRuntime( 5621): 	at androidx.health.platform.client.impl.ReadDataRangeCallback.onError(ReadDataRangeCallback.kt:35)
E/AndroidRuntime( 5621): 	at androidx.health.platform.client.service.IReadDataRangeCallback$Stub.onTransact(IReadDataRangeCallback.java:75)
E/AndroidRuntime( 5621): 	at android.os.Binder.execTransactInternal(Binder.java:1285)
E/AndroidRuntime( 5621): 	at android.os.Binder.execTransact(Binder.java:1244)
E/AndroidRuntime( 5621): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6a98f24, Dispatchers.Main]
```

### Screenshots
![screenshot 2023-06-08 9 56 02](https://github.com/cph-cachet/flutter-plugins/assets/12049405/3332be21-80e6-4b86-9784-6cf3ce68d84b)

**Comment by abdullahkaracabey** [comment]
I got also  this  error.

**Comment by abdullahkaracabey** [comment]
@mototakatsu I found the reason of this bug. You should add intent-filter below in manifest file in activity area. You can see it in example project.
`  <intent-filter>
                <action android:name="androidx.health.ACTION_SHOW_PERMISSIONS_RATIONALE" />
            </intent-filter>`

**Comment by mototakatsu** [comment]
@abdullahkaracabey 
Thank you for the information!!
After adding "androidx.health.ACTION_SHOW_PERMISSIONS_RATIONALE" you introduced, I can now set the authority.

**Comment by chrisvidal** [comment]
facing the same issue even after adding this to the manifest.xml
```
<!-- Check whether Health Connect is installed or not -->
    <queries>
      <package android:name="com.google.android.apps.healthdata" />
      <intent>
          <action android:name="androidx.health.ACTION_SHOW_PERMISSIONS_RATIONALE" />
      </intent>
    </queries>
```

any idea?

**Comment by mototakatsu** [comment]
@chrisvidal 

The sample AndroidManifest file has "ACTION_SHOW_PERMISSIONS_RATIONALE" in two places.
I added "ACTION_SHOW_PERMISSIONS_RATIONALE" to Activity's intent filter.
I didn't add it to queries.

https://github.com/cph-cachet/flutter-plugins/blob/5606be32334777f9e7760eda796bfc7a961a9265/packages/health/example/android/app/src/main/AndroidManifest.xml#L69

**Comment by FebiWilson** [comment]
> @chrisvidal
> 
> The sample AndroidManifest file has "ACTION_SHOW_PERMISSIONS_RATIONALE" in two places. I added "ACTION_SHOW_PERMISSIONS_RATIONALE" to Activity's intent filter. I didn't add it to queries.
> 
> https://github.com/cph-cachet/flutter-plugins/blob/5606be32334777f9e7760eda796bfc7a961a9265/packages/health/example/android/app/src/main/AndroidManifest.xml#L69

Bro I'm still not getting data No idea why my manifest is similar to the example version
