### ISSUE TITLE
[Health] [Crash] onActivityResult "data" parameter can have a null value.

### ISSUE THREAD

**Issue by GwonHyeok** [cph-cachet/flutter-plugins#88]
**Plugin name & version**
health: ^1.0.2

**Describe the bug**
onActivityResult data parameter is nullable but this library isn't nullable

```
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
 	at cachet.plugins.health.HealthPlugin.onActivityResult(Unknown Source:2)
 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:206)
 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:127)
 	at io.flutter.app.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:137)
```

**To Reproduce**
1. if using other flutter plugin 
2. other plugin send null value to data parameter
3. crash app

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale ko-KR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[!] VS Code (version 1.44.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```
**Additional context**

HealthKit

```
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent): Boolean
```
change to

```
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?): Boolean
```

thanks

**Comment by thomasnilsson** [comment]
Fixed in version 1.1.1
